# 전역변수
title: Freethink Values
url: https://soma0sd.github.io/Freethinker-N-Values
github: https://github.com/soma0sd/Freethinker-N-Values
author: soma0sd
email: soma0sd@gmail.com
years: 2017
facebook-app-id: "161236511051720"
facebook-sdk-version: "v2.11"

# 빌드세팅
permalink: pretty
